apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: paystream
  labels:
    app.kubernetes.io/name: auth-service-secrets
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: paystream
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: BANK_API_KEY
      remoteRef:
        key: prod/auth-service
        property: bank-api-key
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/auth-service
        property: db-password
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: prod/auth-service
        property: encryption-key
---
# Staging ExternalSecret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: paystream-staging
  labels:
    app.kubernetes.io/name: auth-service-secrets
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: paystream
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: BANK_API_KEY
      remoteRef:
        key: staging/auth-service
        property: bank-api-key
    - secretKey: DB_PASSWORD
      remoteRef:
        key: staging/auth-service
        property: db-password
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: staging/auth-service
        property: encryption-key
